### ISSUE TITLE
Disconnecting proccess stuck

### ISSUE THREAD

**Issue by iMihael** [randdusing/BluetoothLE#122] opened 2014-12-15 15:54 UTC
Hello, I write bluetooth app and when I tried to disconnect bt module, disconnect process is stuck:

12-15 17:49:03.572: I/chromium(21504): [INFO:CONSOLE(119)] "{"address":"B4:99:4C:67:6D:DA","name":"V2","status":"disconnecting"}", source: file:///android_asset/www/js/controllers/index.js?bust=1418658540959 (119)

debugger write disconnecting status and nothing else.

**Comment by randdusing** [comment] 2015-02-27 00:17
Duplicate of #139 , which was fixed in 2.1.0

**Closed by randdusing** 2015-02-27 00:17 UTC
Labels: pending
